# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/iqcampy',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/iqcampy',
                'lib_path': 'iqcampy'},
  'syms': { 'iqcampy.core': {'iqcampy.core.foo': ('core.html#foo', 'iqcampy/core.py')},
            'iqcampy.storage': { 'iqcampy.storage.compute_reflectance': ( 'reading-iqcam-data.html#compute_reflectance',
                                                                          'iqcampy/storage.py'),
                                 'iqcampy.storage.download': ('reading-iqcam-data.html#download', 'iqcampy/storage.py'),
                                 'iqcampy.storage.filetree': ('reading-iqcam-data.html#filetree', 'iqcampy/storage.py'),
                                 'iqcampy.storage.read_capture': ('reading-iqcam-data.html#read_capture', 'iqcampy/storage.py'),
                                 'iqcampy.storage.read_darkref': ('reading-iqcam-data.html#read_darkref', 'iqcampy/storage.py'),
                                 'iqcampy.storage.read_reflectance': ('reading-iqcam-data.html#read_reflectance', 'iqcampy/storage.py'),
                                 'iqcampy.storage.read_whiteref': ('reading-iqcam-data.html#read_whiteref', 'iqcampy/storage.py')}}}
